name: Build .NET Core 3.0
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
      - run: dotnet publish -c Release
      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./ConsoleApp1/
#      - run: dotnet run --configuration Release --project ./
