name: Build .NET Core 3.0
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
      - run: dotnet publish -c Release -r win10-x64 --self-contained false
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./ConsoleApp1/bin/Release/net6.0-windows/win10-x64/publish/
